### ISSUE TITLE
[Feature Request]: Dockerize Golang-To-Do-App

### ISSUE THREAD

**Issue by vigneshs-dev** [vigneshs-dev/golang-to-do-app#1]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Dockerize the Golang-To-Do-App, so that the project can be implemented in any system without any dependecies.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue
- [ ] I'm willing to provide further clarification or assistance if needed.

**Comment by relaxgameing** [comment]
i would like to try

**Comment by vigneshs-dev** [comment]
Sure. I assign this task to you. You can start your work. Thankyou for your contribution.

**Comment by Gaurav-Krishna-Gaali** [comment]
Let me know if this is open again. I'd also like to contribute.

**Comment by kartik-212004** [comment]
i would like to contribute in this issue

**Comment by vigneshs-dev** [comment]
@relaxgameing was already working on this issue. Both @Gaurav-Krishna-Gaali  and @kartik-212004 can work on this issue. Both of you can show your code and I will try to merge yours works with different branch.

**Comment by vigneshs-dev** [comment]
Hi @relaxgameing .. My deployment failed after merging your branch Bro.. How did you deploy in Railway app with new code. Can you tell me the steps?

**Comment by relaxgameing** [comment]
> Hi @relaxgameing .. My deployment failed after merging your branch Bro.. How did you deploy in Railway app with new code. Can you tell me the steps?

what i am noticing is that the CI workflow is failing as now the go backend has been moved to its own folder (/server) so the CI workflow should be updated 

And for Railway app i just provided the ENV's and it automatically did all the work

**Comment by Gaurav-Krishna-Gaali** [comment]
So it is already done??
